ALTER TABLE `agent_task_record`
    ADD COLUMN `phase` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '任务阶段：PENDING/SCAN/PLAN/EXECUTE/VERIFY/DONE/FAILED' AFTER `task_status`,
    ADD COLUMN `phase_message` VARCHAR(1024) DEFAULT NULL COMMENT '阶段说明' AFTER `phase`,
    ADD COLUMN `batch_size` INT NOT NULL DEFAULT 30 COMMENT '每批候选项数量' AFTER `max_steps`,
    ADD COLUMN `total_items` INT NOT NULL DEFAULT 0 COMMENT '总候选项数量' AFTER `steps`,
    ADD COLUMN `scanned_items` INT NOT NULL DEFAULT 0 COMMENT '已扫描项数量' AFTER `total_items`,
    ADD COLUMN `planned_items` INT NOT NULL DEFAULT 0 COMMENT '已生成计划项数量' AFTER `scanned_items`,
    ADD COLUMN `processed_items` INT NOT NULL DEFAULT 0 COMMENT '已处理项数量' AFTER `planned_items`,
    ADD COLUMN `success_items` INT NOT NULL DEFAULT 0 COMMENT '成功处理项数量' AFTER `processed_items`,
    ADD COLUMN `skipped_items` INT NOT NULL DEFAULT 0 COMMENT '跳过项数量' AFTER `success_items`,
    ADD COLUMN `failed_items` INT NOT NULL DEFAULT 0 COMMENT '失败项数量' AFTER `skipped_items`,
    ADD COLUMN `current_batch` INT NOT NULL DEFAULT 0 COMMENT '当前批次号' AFTER `failed_items`,
    ADD COLUMN `total_batches` INT NOT NULL DEFAULT 0 COMMENT '总批次数' AFTER `current_batch`,
    ADD COLUMN `current_target` VARCHAR(2048) DEFAULT NULL COMMENT '当前处理目标' AFTER `total_batches`;

CREATE TABLE IF NOT EXISTS `agent_task_item` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `task_id` BIGINT NOT NULL COMMENT '任务ID',
    `batch_no` INT DEFAULT NULL COMMENT '批次号',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序号',
    `item_type` VARCHAR(32) NOT NULL COMMENT '条目类型：file/directory',
    `source_path` VARCHAR(2048) NOT NULL COMMENT '当前源路径',
    `target_path` VARCHAR(2048) DEFAULT NULL COMMENT '目标路径',
    `item_status` VARCHAR(32) NOT NULL COMMENT '条目状态：PENDING/RUNNING/SUCCESS/SKIPPED/FAILED',
    `summary` VARCHAR(1024) DEFAULT NULL COMMENT '处理摘要',
    `error_message` LONGTEXT DEFAULT NULL COMMENT '错误信息',
    `processed_at` DATETIME DEFAULT NULL COMMENT '处理时间',
    `create_datetime` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_datetime` DATETIME DEFAULT NULL COMMENT '修改时间',
    `create_user_name` VARCHAR(255) DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` VARCHAR(255) DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` BIGINT DEFAULT NULL COMMENT '修改人ID',
    `create_user_id` BIGINT DEFAULT NULL COMMENT '创建人ID',
    `del_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除 0未删除 1已删除',
    PRIMARY KEY (`id`),
    KEY `idx_agent_task_item_task_id` (`task_id`),
    KEY `idx_agent_task_item_task_status` (`task_id`, `item_status`),
    KEY `idx_agent_task_item_task_batch` (`task_id`, `batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent 任务明细表';
