CREATE TABLE IF NOT EXISTS `playback_reporting_record` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `emby_info_id` bigint DEFAULT NULL COMMENT 'Emby服务器ID',
    `play_day` date NOT NULL COMMENT '播放日期',
    `play_date` datetime NOT NULL COMMENT '播放时间',
    `user_id` varchar(128) DEFAULT NULL COMMENT 'Emby用户ID',
    `user_name` varchar(500) DEFAULT NULL COMMENT 'Emby用户名',
    `nick_name` varchar(500) DEFAULT NULL COMMENT '用户昵称',
    `item_id` int DEFAULT NULL COMMENT '媒体ID',
    `item_name` varchar(1000) DEFAULT NULL COMMENT '媒体名称',
    `item_type` varchar(50) DEFAULT NULL COMMENT '媒体类型',
    `duration` int DEFAULT NULL COMMENT '播放时长，单位秒',
    `remote_address` varchar(128) DEFAULT NULL COMMENT '远程IP地址',
    `location` varchar(255) DEFAULT NULL COMMENT 'IP归属地',
    `poster_url` varchar(1000) DEFAULT NULL COMMENT '海报地址',
    `row_hash` varchar(64) DEFAULT NULL COMMENT '记录去重哈希',
    `create_datetime` datetime DEFAULT NULL COMMENT '创建时间',
    `update_datetime` datetime DEFAULT NULL COMMENT '修改时间',
    `create_user_name` varchar(50) DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` varchar(50) DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` bigint DEFAULT NULL COMMENT '修改人id',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人id',
    `del_flag` int NOT NULL DEFAULT '0' COMMENT '是否删除 0 未删除 1 已删除',
    PRIMARY KEY (`id`),
    KEY `idx_prr_server_day` (`emby_info_id`, `play_day`),
    KEY `idx_prr_server_play_date_id` (`emby_info_id`, `play_date`, `id`),
    KEY `idx_prr_play_date` (`play_date`),
    KEY `idx_prr_user_name` (`user_name`),
    KEY `idx_prr_item_name` (`item_name`(191)),
    KEY `idx_prr_row_hash` (`row_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Playback Reporting播放记录缓存表';

CREATE TABLE IF NOT EXISTS `playback_reporting_sync_day` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `emby_info_id` bigint DEFAULT NULL COMMENT 'Emby服务器ID',
    `play_day` date NOT NULL COMMENT '已同步播放日期',
    `sync_status` int NOT NULL DEFAULT '0' COMMENT '同步状态 0处理中 1成功 2失败',
    `record_count` int NOT NULL DEFAULT '0' COMMENT '同步记录数',
    `synced_at` datetime DEFAULT NULL COMMENT '同步完成时间',
    `error_message` varchar(2000) DEFAULT NULL COMMENT '失败原因',
    `create_datetime` datetime DEFAULT NULL COMMENT '创建时间',
    `update_datetime` datetime DEFAULT NULL COMMENT '修改时间',
    `create_user_name` varchar(50) DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` varchar(50) DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` bigint DEFAULT NULL COMMENT '修改人id',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人id',
    `del_flag` int NOT NULL DEFAULT '0' COMMENT '是否删除 0 未删除 1 已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_prsd_server_day` (`emby_info_id`, `play_day`, `del_flag`),
    KEY `idx_prsd_day_status` (`play_day`, `sync_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Playback Reporting播放记录同步日期表';
