CREATE TABLE IF NOT EXISTS `agent_task_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `task_status` VARCHAR(32) NOT NULL COMMENT '任务状态：PENDING/RUNNING/SUCCESS/FAILED',
    `prompt` LONGTEXT NOT NULL COMMENT '用户原始任务描述',
    `workspace_root` VARCHAR(1024) NOT NULL COMMENT '工作目录根路径',
    `max_steps` INT NOT NULL COMMENT '请求最大步数',
    `dry_run` TINYINT(1) DEFAULT NULL COMMENT '是否预演',
    `steps` INT DEFAULT 0 COMMENT '实际执行步数',
    `final_answer` LONGTEXT DEFAULT NULL COMMENT 'Agent 最终回复',
    `error_message` LONGTEXT DEFAULT NULL COMMENT '失败原因',
    `changed_files_json` LONGTEXT DEFAULT NULL COMMENT '变更文件列表(JSON)',
    `tool_steps_json` LONGTEXT DEFAULT NULL COMMENT '工具步骤列表(JSON)',
    `started_at` DATETIME DEFAULT NULL COMMENT '开始时间',
    `finished_at` DATETIME DEFAULT NULL COMMENT '结束时间',
    `create_datetime` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_datetime` DATETIME DEFAULT NULL COMMENT '修改时间',
    `create_user_name` VARCHAR(255) DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` VARCHAR(255) DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` BIGINT DEFAULT NULL COMMENT '修改人ID',
    `create_user_id` BIGINT DEFAULT NULL COMMENT '创建人ID',
    `del_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除 0未删除 1已删除',
    PRIMARY KEY (`id`),
    KEY `idx_agent_task_status` (`task_status`),
    KEY `idx_agent_task_create_datetime` (`create_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent 异步任务记录表';
