CREATE TABLE IF NOT EXISTS `emby_client_filter_record`
(
    `id`                     BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `emby_info_id`           BIGINT DEFAULT NULL COMMENT '服务器配置ID',
    `emby_server_id`         VARCHAR(100) DEFAULT NULL COMMENT 'Emby服务器ID',
    `server_name`            VARCHAR(255) DEFAULT NULL COMMENT '服务器名称',
    `event_name`             VARCHAR(64) DEFAULT NULL COMMENT 'Webhook事件',
    `emby_user_id`           VARCHAR(100) DEFAULT NULL COMMENT 'Emby用户ID',
    `emby_user_name`         VARCHAR(255) DEFAULT NULL COMMENT 'Emby用户名',
    `session_id`             VARCHAR(100) DEFAULT NULL COMMENT '会话ID',
    `client_name`            VARCHAR(255) DEFAULT NULL COMMENT '客户端名称',
    `device_name`            VARCHAR(255) DEFAULT NULL COMMENT '设备名称',
    `device_id`              VARCHAR(255) DEFAULT NULL COMMENT '设备ID',
    `application_version`    VARCHAR(100) DEFAULT NULL COMMENT '客户端版本',
    `remote_endpoint`        VARCHAR(100) DEFAULT NULL COMMENT '远端地址',
    `item_id`                VARCHAR(100) DEFAULT NULL COMMENT '播放内容ID',
    `item_name`              VARCHAR(500) DEFAULT NULL COMMENT '播放内容名称',
    `item_type`              VARCHAR(64) DEFAULT NULL COMMENT '播放内容类型',
    `matched_pattern`        VARCHAR(255) DEFAULT NULL COMMENT '命中规则',
    `using_default_patterns` TINYINT DEFAULT 0 COMMENT '是否使用代码兜底规则',
    `stop_success`           TINYINT DEFAULT 0 COMMENT '停止播放是否成功',
    `message_success`        TINYINT DEFAULT 0 COMMENT '发送客户端提示是否成功',
    `block_user_enabled`     TINYINT DEFAULT 0 COMMENT '是否开启命中后禁用用户',
    `block_user_success`     TINYINT DEFAULT 0 COMMENT '禁用用户是否成功',
    `notify_sent`            TINYINT DEFAULT 0 COMMENT '是否已尝试发送通知',
    `trigger_time`           DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '触发时间',
    `raw_payload`            LONGTEXT NULL COMMENT '原始Webhook数据',
    `create_datetime`        DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_datetime`        DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `create_user_name`       VARCHAR(50) DEFAULT NULL COMMENT '创建人名称',
    `update_user_name`       VARCHAR(50) DEFAULT NULL COMMENT '修改人名称',
    `create_user_id`         BIGINT DEFAULT NULL COMMENT '创建人id',
    `update_user_id`         BIGINT DEFAULT NULL COMMENT '修改人id',
    `del_flag`               INT DEFAULT 0 COMMENT '是否删除 0 未删除 1 已删除',
    PRIMARY KEY (`id`),
    KEY `idx_trigger_time` (`trigger_time`),
    KEY `idx_emby_info_id` (`emby_info_id`),
    KEY `idx_emby_user_name` (`emby_user_name`),
    KEY `idx_client_name` (`client_name`),
    KEY `idx_session_id` (`session_id`),
    KEY `idx_block_user_success` (`block_user_success`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Emby UA拦截记录';

INSERT INTO `notify_template` (`template_code`, `template_name`, `channel_type`, `template_content`, `variable_comment`, `enabled`, `remark`, `create_datetime`, `update_datetime`, `create_user_name`, `update_user_name`, `update_user_id`, `create_user_id`, `del_flag`)
SELECT 'emby_client_filter', 'UA拦截通知-通用', 'common',
       '${clientFilterDetails}',
       'clientFilterDetails', 1, 'Emby UA拦截命中通知',
       NOW(), NOW(), 'system', 'system', NULL, NULL, 0
WHERE NOT EXISTS (SELECT 1 FROM notify_template WHERE template_code = 'emby_client_filter' AND channel_type = 'common');
