CREATE TABLE `emby_block_keyword`
(
    `id`               bigint       NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `keyword`          varchar(100) NOT NULL COMMENT '关键字',
    `description`      varchar(255)                                                 DEFAULT NULL COMMENT '描述',
    `enabled`          tinyint                                                      DEFAULT '1' COMMENT '是否启用 0-禁用 1-启用',
    `create_datetime`  datetime                                                     DEFAULT NULL COMMENT '创建时间',
    `update_datetime`  datetime                                                     DEFAULT NULL COMMENT '修改时间',
    `create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改人名称',
    `update_user_id`   bigint                                                       DEFAULT NULL COMMENT '修改人id',
    `create_user_id`   bigint                                                       DEFAULT NULL COMMENT '创建人id',
    `del_flag`         int                                                          DEFAULT '0' COMMENT '是否删除 0 未删除 1 已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_keyword` (`keyword`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备屏蔽关键字';

INSERT INTO `emby_block_keyword` (`keyword`, `description`, `enabled`)
VALUES ('4XVR Player', '4XVR Player', 0),
       ('AfuseKt', 'AfuseKt', 0),
       ('AfuseKt/(Linux;Android+Release)Player-TV', 'AfuseKt/(Linux;Android+Release)Player-TV', 0),
       ('Android', 'Android', 0),
       ('AndroidTv', 'AndroidTv', 0),
       ('BeeJoy-Library', 'BeeJoy-Library', 0),
       ('BoxPlayer', 'BoxPlayer', 0),
       ('Conflux', 'Conflux', 0),
       ('DeePlayer', 'DeePlayer', 0),
       ('Emby Theater', 'Emby Theater', 0),
       ('Emby Web', 'Emby Web', 0),
       ('Emby Windows', 'Emby Windows', 0),
       ('Emby Xbox', 'Emby Xbox', 0),
       ('Emby for Android', 'Emby for Android', 0),
       ('Emby for Apple TV', 'Emby for Apple TV', 0),
       ('Emby for Kodi Next Gen', 'Emby for Kodi Next Gen', 0),
       ('Emby for LG', 'Emby for LG', 0),
       ('Emby for Samsung', 'Emby for Samsung', 0),
       ('Emby for iOS', 'Emby for iOS', 0),
       ('Emby for macOS', 'Emby for macOS', 0),
       ('Emby+Web', 'Emby+Web', 0),
       ('Fileball', 'Fileball', 0),
       ('Filebar', 'Filebar', 0),
       ('Filebox', 'Filebox', 0),
       ('Finmony', 'Finmony', 0),
       ('Flymby', 'Flymby', 0),
       ('Forward', 'Forward', 0),
       ('Ghosten Player', 'Ghosten Player', 0),
       ('HamHub Android', 'HamHub Android', 0),
       ('HamHub iOS', 'HamHub iOS', 0),
       ('Hills', 'Hills', 0),
       ('Hills Windows', 'Hills Windows', 0),
       ('Infuse', 'Infuse', 0),
       ('Infuse-Direct', 'Infuse播放器', 0),
       ('Infuse-Library', 'Infuse-Library', 0),
       ('Kodi EmbyCon', 'Kodi EmbyCon', 0),
       ('Lenna', 'Lenna', 0),
       ('MagicalPlayer', 'MagicalPlayer', 0),
       ('MyApp', 'MyApp', 0),
       ('NipaPlay', 'NipaPlay', 0),
       ('Reflix', 'Reflix', 0),
       ('RodelPlayer', 'RodelPlayer', 0),
       ('ScreenSpot_Android.tv.screenspot.global', 'ScreenSpot_Android.tv.screenspot.global', 0),
       ('SenPlayer', 'SenPlayer', 0),
       ('Terminus Player', 'Terminus Player', 0),
       ('Tsukimi', 'Tsukimi', 0),
       ('VidHub', 'VidHub', 0),
       ('VidHub tvOS', 'VidHub tvOS', 0),
       ('VidHub_Android', 'VidHub_Android', 0),
       ('VidHub_OSX', 'VidHub_OSX', 0),
       ('VidHub_iOS', 'VidHub_iOS', 0),
       ('VidHub_tvOS', 'VidHub_tvOS', 0),
       ('Xfuse', 'Xfuse', 0),
       ('Yamby', 'Yamby', 0),
       ('dandanplay', 'dandanplay', 0),
       ('dscloud', 'dscloud', 0),
       ('femor', 'femor', 0),
       ('iPlay', 'iPlay', 0),
       ('montage', 'montage', 0),
       ('picotv', 'picotv', 0),
       ('tvOS', 'tvOS', 0),
       ('zFuse', 'zFuse', 0),
       ('网易爆米花 Android', '网易爆米花 Android', 0),
       ('网易爆米花 iOS', '网易爆米花 iOS', 0);