CREATE TABLE `emby_user_register_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `user_id` BIGINT DEFAULT NULL COMMENT '用户id',
    `emby_user_id` VARCHAR(64) DEFAULT NULL COMMENT 'emby用户id',
    `emby_user_name` VARCHAR(500) DEFAULT NULL COMMENT 'emby用户名',
    `register_channel` TINYINT DEFAULT NULL COMMENT '注册渠道 1 管理员注册 2 卡密注册 3 邀请码注册 4 积分兑换 5 用户注册',
    `emby_info_id` BIGINT DEFAULT NULL COMMENT '服务器地址id',
    `remarks` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `expiration_date` DATETIME DEFAULT NULL COMMENT '到期时间',
    `create_datetime` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_datetime` DATETIME DEFAULT NULL COMMENT '修改时间',
    `create_user_name` VARCHAR(50) DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` VARCHAR(50) DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` BIGINT DEFAULT NULL COMMENT '修改人id',
    `create_user_id` BIGINT DEFAULT NULL COMMENT '创建人id',
    `del_flag` INT DEFAULT 0 COMMENT '是否删除 0 未删除 1 已删除',
    PRIMARY KEY (`id`),
    KEY `idx_register_user_id` (`user_id`),
    KEY `idx_register_channel` (`register_channel`),
    KEY `idx_register_emby_info_id` (`emby_info_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='emby用户注册记录表';

CREATE TABLE `emby_user_renew_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `user_id` BIGINT DEFAULT NULL COMMENT '用户id',
    `emby_user_id` VARCHAR(64) DEFAULT NULL COMMENT 'emby用户id',
    `emby_user_name` VARCHAR(500) DEFAULT NULL COMMENT 'emby用户名',
    `renew_channel` TINYINT DEFAULT NULL COMMENT '续费渠道 1 管理员续费 2 卡密续费',
    `renew_days` INT DEFAULT NULL COMMENT '续费天数',
    `expiration_date_before` DATETIME DEFAULT NULL COMMENT '续费前到期时间',
    `expiration_date_after` DATETIME DEFAULT NULL COMMENT '续费后到期时间',
    `emby_info_id` BIGINT DEFAULT NULL COMMENT '服务器地址id',
    `create_datetime` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_datetime` DATETIME DEFAULT NULL COMMENT '修改时间',
    `create_user_name` VARCHAR(50) DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` VARCHAR(50) DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` BIGINT DEFAULT NULL COMMENT '修改人id',
    `create_user_id` BIGINT DEFAULT NULL COMMENT '创建人id',
    `del_flag` INT DEFAULT 0 COMMENT '是否删除 0 未删除 1 已删除',
    PRIMARY KEY (`id`),
    KEY `idx_renew_user_id` (`user_id`),
    KEY `idx_renew_channel` (`renew_channel`),
    KEY `idx_renew_emby_info_id` (`emby_info_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='emby用户续费记录表';
