-- PT 订阅表（新订阅逻辑）
CREATE TABLE IF NOT EXISTS `movie_pt_subscribe` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` varchar(255) NOT NULL COMMENT '订阅名称',
  `keyword` varchar(255) DEFAULT NULL COMMENT '搜索关键字',
  `type` varchar(20) NOT NULL DEFAULT 'movie' COMMENT '媒体类型（movie/tv）',
  `year` varchar(20) DEFAULT NULL COMMENT '年份',
  `tmdb_id` bigint DEFAULT NULL COMMENT 'TMDB ID',
  `season` int DEFAULT NULL COMMENT '季号（剧集可用）',
  `site_id` bigint DEFAULT NULL COMMENT '指定站点ID（为空时搜索全部启用站点）',
  `scrape_path_config_id` bigint DEFAULT NULL COMMENT '刮削目录配置ID（自动下载必填）',
  `downloader_id` bigint DEFAULT NULL COMMENT '下载器ID（可选）',
  `auto_download` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否自动下载（1是 0否）',
  `enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否启用（1启用 0禁用）',
  `state` varchar(1) NOT NULL DEFAULT 'N' COMMENT '订阅状态 N新建 R订阅中 S暂停',
  `last_matched_count` int NOT NULL DEFAULT 0 COMMENT '最近一次命中数',
  `last_search_time` datetime DEFAULT NULL COMMENT '最近搜索时间',
  `last_download_time` datetime DEFAULT NULL COMMENT '最近下载时间',
  `last_error` varchar(500) DEFAULT NULL COMMENT '最近错误信息',
  `create_datetime` datetime DEFAULT NULL COMMENT '创建时间',
  `update_datetime` datetime DEFAULT NULL COMMENT '修改时间',
  `create_user_name` varchar(50) DEFAULT NULL COMMENT '创建人名称',
  `update_user_name` varchar(50) DEFAULT NULL COMMENT '修改人名称',
  `update_user_id` bigint DEFAULT NULL COMMENT '修改人id',
  `create_user_id` bigint DEFAULT NULL COMMENT '创建人id',
  `del_flag` int DEFAULT '0' COMMENT '是否删除 0 未删除 1 已删除',
  PRIMARY KEY (`id`),
  KEY `idx_movie_pt_subscribe_enabled_state` (`enabled`, `state`, `del_flag`),
  KEY `idx_movie_pt_subscribe_tmdb_id` (`tmdb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='PT订阅表（新订阅逻辑）';
